### ISSUE TITLE
Install broken

### ISSUE THREAD

**Issue by colinmeinke** [brammittendorff/instacraft#3]
Installed with git clone, then went to admin panel InstaCart tab and got the following (line 34 highlighted):

```
Key "criteria" for array with keys "heading" does not exist.

/path/to/craft/plugins/instacraft/templates/index.twig(34)

22 
23         <div class="field" id="assetSource-field">
24             <div class="heading">
25               <label class="required">
26                 {{ "Download Images"|t }}
27               </label>
28               <div class="instructions">{{ "Select a source to pull the instagram images to"|t }} <p></p></div>
29             </div>
30                 <div class="input ltr">
31               {% for source in sources %}
32               <div>
33                     <label>
34                      <input type="radio" value="{{ source.criteria.folderId }}" id="assetSource" name="assetSource" checked="">
35                       {{ source.label }}
36                 </label>
37                 </div>
38               {% endfor %}
39               </div>
40         </div>
41 
42         <div class="buttons">
43                 <input type="submit" class="btn submit" value="{{ 'Download'|t }}">
44             </div>
45       </form>
46     </p>
```

**Comment by brammittendorff** [comment]
Let me verify this. I will be soon back with an answer.

**Comment by brammittendorff** [comment]
Hi there I verified it and it is indeed broken. The source selection has a different name i'm going to fix this now.

**Comment by brammittendorff** [comment]
You should try to create a source and make it writable. I created a test folder in the `public_html` and used the command `chmod 754 test/`. After that I tried to download the files and it worked.

![alt text](http://preview.ibb.co/fMAQ7m/working.png "Working")

Could you give me your version of craft or the steps for me to reproduce this problem?

Kinds and regards,

~$Bram

**Comment by brammittendorff** [comment]
It has been a long time with no specified steps to reproduce this problem closing for now.
