### ISSUE TITLE
Undefined property: stdClass::$user error on Download

### ISSUE THREAD

**Issue by romainpoirier** [brammittendorff/instacraft#4]
It seems that the Instagram API has changed, and now the plugin is broken: it fails to import pictures.

After click on Download, I get this error:

```
Internal Server Error
Undefined property: stdClass::$user
```

**Craft version:** 2.6.3012 _(latest version at this time of writing)_
**Plugin version:** InstaCraft 1.0.5 _(latest version at this time of writing)_

**Comment by grndsgn** [comment]
@romainpoirier I have a pending pull request that will get you back up and running [here](https://github.com/brammittendorff/instacraft/pull/5)

**Comment by brammittendorff** [comment]
@romainpoirier @greendesigned Merged and tagged thanks to both of you :smile:
